apiVersion: apps/v1
kind: Deployment
metadata:
  name: technical-indicators
  labels:
    app: technical-indicators
spec:
  replicas: 1
  selector:
    matchLabels:
      app: technical-indicators
  template:
    metadata:
      labels:
        app: technical-indicators
    spec:
      containers:
        - name: technical-indicators
          image: technical_indicators:dev
          imagePullPolicy: Never
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
          env:
            - name: KAFKA_BROKER_ADDRESS
              value: "kafka-0.kafka-headless.kafka.svc.cluster.local:9092"
            - name: KAFKA_INPUT_TOPIC
              value: "candles"
            - name: KAFKA_OUTPUT_TOPIC
              value: "features"
            - name: KAFKA_CONSUMER_GROUP
              value: "technical-indicators-service"
            - name: LOG_FORMAT
              value: "text"
